name: 'Attach Branch'
description: 'Attach branch'
inputs:
  card-id: 
    description: 'Trello card id'
    required: false
    default: ''

  key: 
    description: 'Trello key'
    required: true
    default: '-1'

  token:
    description: 'Trello token'
    required: true
    default: '-1'

  attachment-type:
    description: 'Types of url to attachme, the value of "branch" or "commit".'
    required: false
    default: 'commit'

runs:
  using: 'node12'
  main: 'index.js'